import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:uuid/uuid.dart';
import '../services/storage_service.dart';
import '../services/firestore_service.dart';
import '../models/image_data.dart';

class UploadScreen extends StatefulWidget {
  const UploadScreen({super.key});

  @override
  State<UploadScreen> createState() => _UploadScreenState();
}

class _UploadScreenState extends State<UploadScreen> {
  File? _imageFile;
  bool _isPublic = true;
  bool _isAdultContent = false;
  bool _isUploading = false;
  final ImagePicker _picker = ImagePicker();

  Future<void> _pickImage() async {
    final XFile? pickedFile = await _picker.pickImage(
      source: ImageSource.gallery,
    );
    if (pickedFile != null) {
      setState(() {
        _imageFile = File(pickedFile.path);
      });
    }
  }

  Future<void> _uploadImage() async {
    if (_imageFile == null) return;

    setState(() {
      _isUploading = true;
    });

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) throw Exception('User not logged in');

      final storageService = Provider.of<StorageService>(
        context,
        listen: false,
      );
      final firestoreService = Provider.of<FirestoreService>(
        context,
        listen: false,
      );

      // 1. Upload file to Storage
      final String downloadUrl = await storageService.uploadImage(
        file: _imageFile!,
        userId: user.uid,
      );

      // 2. Save metadata to Firestore
      final imageData = ImageData(
        id: const Uuid().v4(), // We can use the doc ID as the ID
        uploaderId: user.uid,
        url: downloadUrl,
        isPublic: _isPublic,
        isAdultContent: _isAdultContent,
        timestamp: DateTime.now(),
      );

      // Note: We should probably use the ID generated by Firestore or the one we generated.
      // Here I'm generating one but FirestoreService.addImageMetadata uses the ID from the object.
      await firestoreService.addImageMetadata(imageData);

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Image uploaded successfully!')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Upload failed: $e')));
      }
    } finally {
      if (mounted) {
        setState(() {
          _isUploading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Upload Image')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            GestureDetector(
              onTap: _pickImage,
              child: Container(
                height: 200,
                decoration: BoxDecoration(
                  color: Colors.grey[200],
                  border: Border.all(color: Colors.grey),
                  borderRadius: BorderRadius.circular(8),
                ),
                child:
                    _imageFile != null
                        ? Image.file(_imageFile!, fit: BoxFit.cover)
                        : const Icon(
                          Icons.add_a_photo,
                          size: 50,
                          color: Colors.grey,
                        ),
              ),
            ),
            const SizedBox(height: 16),
            SwitchListTile(
              title: const Text('Public'),
              subtitle: const Text('Visible to everyone'),
              value: _isPublic,
              onChanged: (val) => setState(() => _isPublic = val),
            ),
            SwitchListTile(
              title: const Text('Adult Content (18+)'),
              subtitle: const Text('Contains sensitive material'),
              value: _isAdultContent,
              onChanged: (val) => setState(() => _isAdultContent = val),
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed:
                  _isUploading || _imageFile == null ? null : _uploadImage,
              child:
                  _isUploading
                      ? const CircularProgressIndicator()
                      : const Text('Upload'),
            ),
          ],
        ),
      ),
    );
  }
}
